enum TextContents {
  account,
  accountUsernameEntry,
  addHabit,
  addPartnerInstructions,
  appName,
  back,
  calendar,
  calendarRecordScreenDescription,
  cancel,
  cannotApprovePartner,
  cannotInputDuringUpdate,
  cannotSendToSelf,
  changeAccountPassword,
  changeAccountUsername,
  changePassword,
  changeThemeColor,
  changeUsername,
  checked,
  checkEmail,
  clear,
  complete,
  confirmApproval,
  confirmDelete,
  confirmHabitDelete,
  confirmLogout,
  confirmPartnerRemoval,
  confirmPassword,
  confirmRejection,
  confirmWithdrawal,
  confirmWithdrawalAction,
  createRecord,
  cumulative,
  cumulativeValue,
  cumulativeValuePrefix,
  currentTime,
  currentValue,
  date,
  dataType,
  dateFormat,
  dateFormatYMD,
  delete,
  deleteAccountWarning,
  deleteHabitInfo,
  editHabit,
  emailAddress,
  emailAddressFormatError,
  emailConfirmationComplete,
  emailConfirmationInstructions,
  emailConfirmed,
  emailSentSuccess,
  enterCurrentEmail,
  enterCurrentValue,
  enterDeadline,
  enterEmail,
  enterGoalDegree,
  enterGoalTitle,
  enterGoalValue,
  enterHabitTitle,
  enterMemo,
  enterPartnerId,
  enterUnit,
  enterValue,
  errorOccurred,
  forgotPassword,
  formattedDate,
  futureDateError,
  goal,
  goalAchieved,
  goalAchievementScreenDescription,
  goalDeadline,
  goalExample,
  goalExistence,
  goalExistenceNo,
  goalExistenceYes,
  goalNotSet,
  goalProgress,
  goalResetWarning,
  goalValue,
  goalValuePrefix,
  greaterThanCurrentValue,
  habitExample,
  habitGoalAchievementScreen,
  habitLimitReached,
  habitManagementByMonth,
  habitPrivate,
  habitProgressAndAccumulationManagement,
  habitPublic,
  habitTutorialReference,
  habitType,
  habitTypePrivate,
  habitTypePublic,
  home,
  hour,
  icon,
  iconList,
  initialScreen,
  lessThanCurrentValue,
  license,
  loading,
  login,
  loginOnlyItem,
  loginPrompt,
  loginRequiredToChangeHabitType,
  logout,
  manageHabitInfo,
  menuBarDescription,
  minute,
  myHabitTab,
  newAccountOnlyMessage,
  noDataFound,
  noHabit,
  noInternet,
  none,
  nonLoginOnlyItem,
  noPartner,
  noPublicHabit,
  noRequests,
  note,
  noUnitForDataType,
  ok,
  one,
  openMenuAndRegisterPartner,
  others,
  partner,
  partnerAlreadyLimits,
  partnerApprovalInstructions,
  partnerApprovalProcess,
  partnerHabitReadOnly,
  partnerHabitTab,
  partnerId,
  partnerLimitNote,
  partnerRegisteredConfirmation,
  partnerRequest,
  password,
  passwordConfirmationEntry,
  passwordEntryInstructions,
  passwordResetEmailDescription,
  passwordResetEmailSent,
  pastDateError,
  performLogin,
  performLogout,
  pleaseLogin,
  privacyPolicy,
  reauthRequiredForWithdrawal,
  record,
  recordForMonth,
  recordYourHabitPrompt,
  register,
  registerPartnerInstructions,
  requestPartner,
  requestSent,
  requiredFieldsNote,
  resendConfirmationEmail,
  save,
  second,
  selectHabitVisibility,
  sendConfirmationEmail,
  sendPasswordResetLink,
  setCumulative,
  setDataType,
  setGoal,
  setGoalValue,
  setHabitIcon,
  settings,
  shareHabitsWithPartnerInstructions,
  shortTimeZero,
  tapToEnter,
  tapToEnterDate,
  taskDone,
  taskNotDone,
  taskNotDoneNewLine,
  termsOfService,
  theme,
  timeZero,
  title,
  trackAllHabitsScreenDescription,
  trackHabitsByMonthDescription,
  tutorial,
  tutorialInfo,
  unexpectedError,
  unit,
  unregister,
  updatePassword,
  updateUsername,
  username,
  userNotRegistered,
  value,
  viewLicenseInfo,
  viewPartnerHabitInfo,
  viewPrivacyPolicy,
  viewTermsOfService,
  withdraw,
  withdrawalComplete,
  yourEmail,
  yourId,
  yourPartnerIsLimit,
  zero,
  zeroFew,
}

extension TextContentsExtension on TextContents {
  static const Map<TextContents, String> _texts = {
    TextContents.account: 'アカウント',
    TextContents.accountUsernameEntry:
        '・あなたのアカウントのユーザー名を入力してください。ユーザー名はパートナーへ共有してされます。',
    TextContents.addHabit: '習慣の追加',
    TextContents.addPartnerInstructions: 'パートナーの新規登録',
    TextContents.appName: 'UrHabits',
    TextContents.back: '戻る',
    TextContents.calendar: 'カレンダー',
    TextContents.calendarRecordScreenDescription: '記録画面(カレンダー)',
    TextContents.cancel: 'キャンセル',
    TextContents.cannotApprovePartner: 'このユーザーは既に別のパートナーが存在するので、承認できません',
    TextContents.cannotInputDuringUpdate: '更新時は入力できません',
    TextContents.cannotSendToSelf: '自分自身に送信することはできません',
    TextContents.changeAccountPassword: '・ログインしてるアカウントのパスワードを変更できます。',
    TextContents.changeAccountUsername: '・ログインしてるアカウントのユーザー名を変更できます。',
    TextContents.changePassword: 'パスワードの変更',
    TextContents.changeThemeColor: '・テーマカラーを変更できます。',
    TextContents.changeUsername: 'ユーザー名の変更',
    TextContents.checked: 'Checked!',
    TextContents.checkEmail: 'メールを確認してください',
    TextContents.clear: 'クリア',
    TextContents.complete: '完了',
    TextContents.confirmApproval: '承認しますか？',
    TextContents.confirmDelete: '削除しますか？',
    TextContents.confirmHabitDelete: 'この習慣を削除します\nよろしいでしょうか？',
    TextContents.confirmLogout: 'ログアウトしますか？',
    TextContents.confirmPartnerRemoval: 'を解除しますか？',
    TextContents.confirmPassword: 'パスワード\n(確認用)',
    TextContents.confirmRejection: '拒否しますか？',
    TextContents.confirmWithdrawal: '「UrHabits」から退会しますよろしいでしょうか？',
    TextContents.confirmWithdrawalAction: '退会する',
    TextContents.createRecord: '記録を作成',
    TextContents.cumulative: '累積',
    TextContents.cumulativeValue: '累積値',
    TextContents.cumulativeValuePrefix: '累積値：',
    TextContents.currentTime: '現在時刻',
    TextContents.currentValue: '現在値',
    TextContents.date: '日付',
    TextContents.dataType: 'データタイプ',
    TextContents.dateFormat: 'yyyy年M月',
    TextContents.dateFormatYMD: 'yyyy/M/d',
    TextContents.delete: '削除',
    TextContents.deleteAccountWarning: 'ユーザーアカウントと公開用に保存された習慣を完全に削除します。'
        '削除せずに残しておく場合は次の操作をしてください。\n'
        '※ 習慣を削除したくない場合は、「ホーム画面」の公開習慣から習慣編集アイコンをタップ→「習慣の編集画面」の「習慣種別」を「公開」→「非公開」としておくと削除されません',
    TextContents.deleteHabitInfo: '※更新時の場合は左下に表示される「ゴミ箱」ボタンで習慣の削除ができます。',
    TextContents.editHabit: '習慣の編集',
    TextContents.emailAddress: 'メールアドレス',
    TextContents.emailAddressFormatError: '・正しい形式のメールアドレスを入力してください。',
    TextContents.emailConfirmationComplete: 'メールの確認が完了しました',
    TextContents.emailConfirmationInstructions:
        '※確認メールを送信後、「メール確認完了」ボタンが表示されるので、こちら押下後はホーム画面に遷移します。',
    TextContents.emailConfirmed: 'メール確認完了',
    TextContents.emailSentSuccess: 'メールの送信が完了しました',
    TextContents.enterCurrentEmail: '現在ログインしているユーザーのメールアドレスを入力してください。',
    TextContents.enterCurrentValue:
        '・あなたの習慣の現在値を入力してください\n※特に記録がない場合は、入力しなくても問題ないです。',
    TextContents.enterDeadline:
        '・いつまでに達成したいかを入力してください。\n※入力できる日付は、本日か未来日のみとなっています。',
    TextContents.enterEmail: 'メールアドレスを入力してください。',
    TextContents.enterGoalDegree: '・目標の度合いを入力してください。'
        '前画面の「習慣の追加」で「累積」が正の累積の場合は「現在の値より大きい」、'
        '負の累積の場合は「現在の値より小さい」、'
        '累積しないの場合は、上記のどちらかが入力可能です。',
    TextContents.enterGoalTitle: '・あなたの目標のタイトルを入力してください',
    TextContents.enterGoalValue: '・目標値を入力してください。\n※目標の度合いによって変える必要があります。'
        '目標の度合いが「現在値より大きい」場合は、現在値より大きい値を、'
        '「現在値より小さい」場合は、小さい値を入力してください。',
    TextContents.enterHabitTitle: '・あなたの習慣のタイトルを入力してください',
    TextContents.enterMemo: '・目標を達成する上で必要なメモを記入してください。',
    TextContents.enterPartnerId: 'パートナーIDを入力',
    TextContents.enterUnit: '・習慣を記録するときの単位を設定できます。',
    TextContents.enterValue: '値を入力してください',
    TextContents.errorOccurred: 'エラーが起きました',
    TextContents.forgotPassword: 'パスワードを忘れた方はこちら',
    TextContents.formattedDate: 'yyyy年M月d日',
    TextContents.futureDateError: '本日より後の日付は\n選択できません',
    TextContents.goal: '目標',
    TextContents.goalAchieved: '目標達成',
    TextContents.goalAchievementScreenDescription: '記録画面(目標達成)',
    TextContents.goalDeadline: '目標期日',
    TextContents.goalExample: '例）3月までに300回する',
    TextContents.goalExistence: '目標有無',
    TextContents.goalExistenceNo: 'なし',
    TextContents.goalExistenceYes: 'あり',
    TextContents.goalNotSet: '設定されていません',
    TextContents.goalProgress: '目標の度合い',
    TextContents.goalResetWarning: '既に目標が設定されている場合、\nこの項目を変更すると目標が\n初期化されます',
    TextContents.goalValue: '目標値',
    TextContents.goalValuePrefix: '目標値：',
    TextContents.greaterThanCurrentValue: '現在値より大きい',
    TextContents.habitExample: '例）腹筋トレーニング',
    TextContents.habitGoalAchievementScreen:
        '習慣の目標達成状況が、確認できる画面です。いままで記録した習慣が確認できます。',
    TextContents.habitLimitReached: '習慣の公開できる数が上限に達しました',
    TextContents.habitManagementByMonth:
        '・月ごとの習慣を管理できます。本日は数字の周りは赤く表示され、目標日は黄色の枠で覆われます。(目標日の設定がない場合は表示なし)',
    TextContents.habitPrivate: '非公開 (個人の習慣)',
    TextContents.habitProgressAndAccumulationManagement:
        '・目標の達成具合と今までの習慣について管理します。表示形式は、「累積」と「目標」の設定によって変化します。',
    TextContents.habitPublic: '公開 (パートナーへ共有する習慣)',
    TextContents.habitTutorialReference:
        '※「習慣記録画面」の詳しい 操作方法は「設定」の「チュートリアル」をご覧下さい。',
    TextContents.habitType: '習慣種別',
    TextContents.habitTypePrivate: '非公開',
    TextContents.habitTypePublic: '公開',
    TextContents.home: 'ホーム',
    TextContents.hour: '時',
    TextContents.icon: 'アイコン',
    TextContents.iconList: 'アイコン一覧',
    TextContents.initialScreen: '初期画面',
    TextContents.lessThanCurrentValue: '現在値より小さい',
    TextContents.license: 'ライセンス',
    TextContents.loading: 'ロード中...',
    TextContents.login: 'ログイン',
    TextContents.loginOnlyItem: '※ログイン時のみ表示される項目',
    TextContents.loginPrompt:
        'まずはログインからしてみましょう。アカウントがない場合はメールアドレスを利用して新規登録をしてください。',
    TextContents.loginRequiredToChangeHabitType: '習慣種別を変更するにはログインする必要があります',
    TextContents.logout: 'ログアウト',
    TextContents.manageHabitInfo: '・あなたの習慣の追加、更新などができます。'
        'あなたの習慣は非公開、公開習慣に分けられ、公開習慣として登録するとパートナーへ公開されます。',
    TextContents.menuBarDescription: 'メニューバー',
    TextContents.minute: '分',
    TextContents.myHabitTab: 'わたしの習慣',
    TextContents.newAccountOnlyMessage: '※新規登録時のみ表示される項目',
    TextContents.noDataFound: 'データが見つかりません。',
    TextContents.noHabit: '習慣がありません',
    TextContents.noInternet: 'インターネットの接続がありません、電波の良い場所でお試しください',
    TextContents.nonLoginOnlyItem: '※非ログイン時のみ表示される項目',
    TextContents.noPartner: 'パートナーがいません',
    TextContents.noRequests: '依頼はありません',
    TextContents.note: 'メモ',
    TextContents.noUnitForDataType: 'このデータタイプは単位を入力できません',
    TextContents.ok: 'OK',
    TextContents.one: '1',
    TextContents.openMenuAndRegisterPartner: 'メニューを開いて、パートナーを登録して習慣を共有してみましょう。',
    TextContents.others: 'その他',
    TextContents.partner: 'パートナー',
    TextContents.partnerAlreadyLimits: '送ろうとしているパートナー\nのパートナー数が上限に達しています',
    TextContents.partnerApprovalInstructions: 'パートナーの承認',
    TextContents.partnerApprovalProcess: '申請したらパートナーに登録してもらって登録は完了です。',
    TextContents.partnerHabitReadOnly: 'パートナーの習慣は\n読み取り専用です',
    TextContents.partnerHabitTab: 'パートナーの習慣',
    TextContents.partnerId: 'パートナーID',
    TextContents.partnerLimitNote: '※パートナーの登録は一人のみです。',
    TextContents.partnerRegisteredConfirmation: '無事にパートナーが登録されました。',
    TextContents.partnerRequest: 'パートナー依頼',
    TextContents.password: 'パスワード',
    TextContents.passwordConfirmationEntry: '・入力したパスワードを再度、確認用で入力してください。',
    TextContents.passwordEntryInstructions:
        '・パスワードを入力してください。形式は半角英数字の6文字以上で入力してください',
    TextContents.passwordResetEmailDescription:
        '登録済みのメールアドレスにパスワード変更のリンクを送信します。',
    TextContents.passwordResetEmailSent: 'パスワードの再設定メールの送信が完了しました',
    TextContents.pastDateError: '本日より前の日付は\n選択できません。',
    TextContents.performLogin: '・ログインすることができます。',
    TextContents.performLogout: '・ログアウトができます。',
    TextContents.pleaseLogin: 'ログインしてください',
    TextContents.privacyPolicy: 'プライバシーポリシー',
    TextContents.reauthRequiredForWithdrawal:
        '退会する場合は再認証する必要があるためメールアドレスとパスワードを入力してください。',
    TextContents.record: '記録',
    TextContents.recordForMonth: 'M月の記録',
    TextContents.recordYourHabitPrompt: 'さぁ、あなたの習慣を\n記録しよう!',
    TextContents.register: '新規登録',
    TextContents.registerPartnerInstructions:
        'ログインしたらパートナーを登録しましょう。パートナーを追加するには画面下のIDが必要になります。パートナーと連絡をとりあって、IDを教えてもらいましょう。',
    TextContents.requestPartner: 'パートナーを申請する',
    TextContents.requestSent: '申請しました',
    TextContents.requiredFieldsNote: '※アスタリスク(*)がついている項目は、入力が必須です。',
    TextContents.resendConfirmationEmail: '確認メールを再送信',
    TextContents.save: '保存',
    TextContents.second: '秒',
    TextContents.selectHabitVisibility: '・習慣の公開、非公開を選択できます。'
        '公開は登録したパートナーへ公開されます。'
        '\n※習慣を公開するためにはログインする必要があります。また公開できる習慣は最大で3項目までです。',
    TextContents.sendConfirmationEmail: '確認メールを送信',
    TextContents.sendPasswordResetLink: 'メールを送信してパスワードを変更する',
    TextContents.setCumulative: '・習慣を記録するときの累積するかどうか設定できます。'
        '正の累積の場合は、記録した習慣が今まで入力した記録に加算されます。'
        '負の累積は記録した習慣が今まで入力した記録に減算されます。'
        '累積しない場合は特に加算や減算はしないです。',
    TextContents.setDataType: '・習慣を記録するときのデータタイプが設定できます。'
        'データタイプごとに入力形式が異なります。',
    TextContents.setGoal: '・目標を設定するかどうかを決められます。',
    TextContents.setGoalValue: '・あなたの習慣に適した目標値を設定できます。自由に設定してみてください。',
    TextContents.setHabitIcon: '・あなたの習慣にあったアイコンを設定できます。',
    TextContents.settings: '設定',
    TextContents.shareHabitsWithPartnerInstructions:
        'これでパートナーとともにあなたの目標を達成してみましょう。',
    TextContents.shortTimeZero: '00:00',
    TextContents.tapToEnter: 'タップして入力',
    TextContents.tapToEnterDate: '日付を選択',
    TextContents.taskDone: 'Done',
    TextContents.taskNotDone: 'Not Done',
    TextContents.taskNotDoneNewLine: 'Not\nDone',
    TextContents.termsOfService: '利用規約',
    TextContents.theme: 'テーマ',
    TextContents.timeZero: '00:00:00',
    TextContents.title: 'タイトル',
    TextContents.trackAllHabitsScreenDescription:
        'すべての習慣を管理できる画面です。図のような操作（記録、更新、追加）ができます。あなたの習慣を追加して記録してみましょう。',
    TextContents.trackHabitsByMonthDescription:
        '月ごとにあなたの習慣が管理できます。習慣の追加は、カレンダーか左下の追加ボタンから追加できます。更新する場合は、カレンダーか記録リストから選択して更新できます。',
    TextContents.tutorial: 'チュートリアル',
    TextContents.tutorialInfo:
        '※「ホーム画面」、「メニューバー」の詳しい操作方法は「設定」の「チュートリアル」をご覧下さい。',
    TextContents.unexpectedError: '予期せぬエラーが起きました',
    TextContents.unit: '単位',
    TextContents.unregister:
        '・ログインしているアカウントを「UrHabits」から退会させます。\n※退会するとアカウント情報と公開習慣がすべて削除されます。',
    TextContents.updatePassword: 'パスワードを変更する',
    TextContents.updateUsername: 'ユーザー名を変更する',
    TextContents.username: 'ユーザー名',
    TextContents.userNotRegistered: '入力したユーザーが\n登録されていません',
    TextContents.value: '値',
    TextContents.viewLicenseInfo: '・「UrHabits」のライセンスを確認できます。',
    TextContents.viewPartnerHabitInfo: '・登録したパートナーの習慣を見ることができます。'
        'パートナーはログインしてからパートナー申請をすることで登録することができます。'
        '※パートナーの習慣に記録することはできません。読み取り専用です。',
    TextContents.viewPrivacyPolicy: '・「UrHabits」のプライバシーポリシーを確認できます。',
    TextContents.viewTermsOfService: '・「UrHabits」の利用規約を確認できます。',
    TextContents.withdraw: '退会',
    TextContents.withdrawalComplete: '退会が完了しました',
    TextContents.yourEmail: 'メールアドレス ',
    TextContents.yourId: 'あなたのID ',
    TextContents.yourPartnerIsLimit: 'パートナー数が上限に達しています',
    TextContents.zero: '0',
    TextContents.zeroFew: '0.0',
  };

  String get text => _texts[this] ?? '';
}
